---
title: "《知情同意书》"
output: 
  html_document:
    toc: true
    toc_float: true
---

----------
<p style="text-indent: 30px">我们将要开展一项研究“新冠康复患者实际恢复情况”，您的具体情况符合本项研究的入组条件，因此，我们邀请您参加本项研究。本知情同意书将向您介绍本项研究的目的、步骤、获益和风险等，请仔细阅读后决定是否参加。当研究者向您说明和讨论知情同意书时，您可以随时提问并要求他/她向您解释您不明白的地方。您可以与家人、朋友以及您的经治大夫讨论之后再做决定。</p>

<p style="text-indent: 30px">本项研究的项目负责人是 《知情同意书》撰写方。</p>

----------

### 1．为什么进行本项研究？
<p style="text-indent: 30px">尊敬的受访者，您好！我们是来自世界各地高校学生组成的研究小组。我们的组员分别来自于复旦大学，东华大学，中国药科大学，哥伦比亚大学，布兰迪斯大学等。现在新冠疫情在中国已经受到很好的控制，需要为国家与大家的积极响应喝彩。但是即便新冠病毒在逐渐消失，感染过患者的身体机能在不同程度上都受到了负面影响。自新冠肺炎爆发以来，各类报道与研究文献通过观察与检测对新冠康复患者的身体机能，例如心肺，消化系统，生殖系统等，发现受新冠病毒在感染期间影响的器官不仅仅局限于肺部，而可能涉及各大器官。由于新冠患者的随访调查尚未组成一个大型的官方统计报告，我们对新冠患者的实际康复情况，其中包含新冠导致的器官功能损失，没有一个客观与全面的认知。我们研究组希望通过新冠康复患者获得统计数据，结合病理及免疫学，从宏观与微观的角度研究导致新冠患者受不同程度影响的原因。 为了了解新冠病毒感染者康复情况及其影响因素，更好地为新型冠状病毒流行防控与肺炎诊治提供依据，我们特开展本次问卷调查，恳请您用几分钟时间帮忙填答这份问卷，希望能得到您的真实情况与宝贵意见。
<p style="text-indent: 30px">结合本问卷实行匿名制，所有数据只用于统计分析，我们向您承诺隐私保护，请您放心填写。题目选项无对错之分，请您按自己的实际情况填写。谢谢您的合作与帮助！如希望得到研究结果反馈，也可在问卷最后提供您的联系方式！</p>

### 2．哪些人将被邀请参加本项研究？
<p style="text-indent: 30px">感染过新型冠状肺炎并康复的人。</p>

### 3．多少人将参与本项研究？
<p style="text-indent: 30px">本项研究计划招募   500  名受试者。</p>

### 4．本项研究包括哪些内容？
<p style="text-indent: 30px">问卷调查的内容，包括对受访者生理及心理的定性与半定量问卷调查。</p>

### 5．本项研究会持续多久？
<p style="text-indent: 30px">三个月 </p>

### 6．参加本项研究的风险是什么？
<p style="text-indent: 30px">问卷中的某些问题可能会让您感到不舒服，您可以拒绝回答。</p>

### 7．参加本项研究的获益是什么？
<p style="text-indent: 30px">您不会因参加本项研究有直接获益，您的参与有助于了解新冠病毒感染者康复情况及其影响因素，更好地为新型冠状病毒流行防控与肺炎诊治提供依据。</p>

### 8．是否一定要参加并完成本项研究？
<p style="text-indent: 30px">您是否参加这个研究完全是自愿的。如果您不愿意，可以拒绝参加，这对您目前或未来的医疗不会有任何负面影响。即使您同意参加以后，您也可以在任何时间改变主意，告诉研究者退出研究，您的退出不会影响您获得正常的医疗服务。</p>

<p style="text-indent: 30px">原则上，研究者将严密保存您退出研究前的相关信息，直至最终销毁，不会继续使用或透露。但在极少数情况下需使用这些信息，例如政府监管部门进行监督、检查、统计时，会要求查看所有研究信息，其中会包括您当时参与研究的相关信息等。</p>

### 9．参加该项研究的费用和补偿
<p style="text-indent: 30px"> 本项研究不涉及任何费用和补偿。</p>

### 10．发生研究相关伤害的处理？
<p style="text-indent: 30px"> 本项研究不会对您的身体健康造成任何伤害。</p>

### 11．我的信息会保密吗？
<p style="text-indent: 30px">如果您决定参加本项研究，您参加研究及在研究中的个人资料均属保密。可以识别您身份的信息将不会透露给研究成员以外的人员，除非获得您的许可。所有的研究成员都被要求对您的身份保密。您的档案将保存在有锁的档案柜中，仅供研究人员查阅。为确保研究按照规定进行，必要时，政府管理部门或伦理委员会的成员按规定可以在研究单位查阅您的个人资料。本项研究结果发表时，将不会披露您个人的任何资料。</p>

### 12．如果有问题或困难，该与谁联系？
<p style="text-indent: 30px">如果您有与本项研究相关的任何问题，请联系张先生，联系电话13418732286。</p>

----------

### 13．签字    

#### 研究者声明
<p style="text-indent: 30px">我已向受试者（和法定代理人）讲解了（新冠康复患者实际恢复情况）本项研究的背景、目的、步骤、风险及获益情况，给予他/她足够的时间阅读知情同意书、与他人讨论，并解答了其提出的有关本项研究的问题；我告诉了该受试者遇到与研究相关问题时的联系方式；我告诉了该受试者（或法定代理人）他/她可以在研究期间的任何时候无需任何理由退出本项研究。</p>
 
<p style="text-indent: 30px"> 研究者签名：___________            日期：___________ </p>

#### 受试者声明
<p style="text-indent: 30px">研究者向我说明了（新冠康复患者实际恢复情况）的研究背景、目的、步骤、风险及获益事项，我有足够的时间和机会提出问题，研究者做出的解答我很满意。我知道当我有问题或想进一步获得信息应当与谁联系。我阅读了这份知情同意书，决定参加本项研究。我知道我可以在研究期间的任何时候无需任何理由都可以退出本项研究。我被告知我将得到这份知情同意书的副本，上面包含我和研究者的签名。</p>

<p style="text-indent: 30px"> 受试者签名： ___________           日期： ___________ </p>


 **备注：**
 
 <p style="text-indent: 30px">1.当受试者为无民事行为能力或限制民事行为能力人时，由其法定代理人签字。</p>
 <p style="text-indent: 30px">法定代理人签字【如适用】： ___________      日期： ___________   与受试者关系： ___________ </p>
 

